# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/PASSSummit2019.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  versionNumber: '$(MajorVersion).$(MinorVersion).$(Revision)-$(build.SourceBranchName)-$(GitVersion.ShortSha)'
  my-counter: '$(MinorVersion)'
  Revision: $[counter(variables['my-counter'],0)]